### ISSUE TITLE
As a user I'd like to have templates imported and started so I can bootstrap my NiFi instance

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/nifi-operator#206]
I'd like to be able to specify a XML NiFi template that I want to import into NiFi.
Optionally I'd like to add and start it immediately after the import.
This will probably be a new CRD.

Templates (probably) do include controller services but they do not contain the actual secrets (e.g. database credentials).

The import should be a one-time import. Once its imported it should not be changed again which means the status needs to be recorded somewhere.

The scope of this ticket is to just import a XML template.
We'll create a follow-up ticket to deal with secrets.

There are multiple options on where the actual XML could come from:
- 1) A field in the CRD
- 2) A ConfigMap/Secret referenced in the CRD
- 3) A HTTP(S) URL
- 4) A git reference (repo, tag, branch, path, I don't know)

Please implement option 1 and/or 2! I don't have a preference, if you're unsure bring it up in the architecture meeting.
The others are optional.

Acceptance criteria
- [ ] Import XML template into running NiFi 
- [ ] Documentation added for new feature
- [ ] Example added
- [ ] Integration test, ideally in collaboration with Simon to test two systems together

**Comment by Jimvin** [comment]
To this end we should do the following 
- Import a NiFi flow template
- Create and populate a parameter context
- Create a process group and link the template and param context to it
- Deploy the workflow into the process group
- Schedule the process group

**Comment by soenkeliebau** [comment]
I have done a bit of thinking and designing around this and would like to re-litigate whether this is something that we actually need to code into the operator because people will actually use it, or if we can get by with a lower-tech solution for our demo purposes.

The solution I came up with to make this useful looks roughly like the following:

```yaml
---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiFlow
metadata:
  name: simple-flow
spec:
  targetNifi: "simple-nifi"
  templateConfigMap: "ingest-flow-template"
  parameterContextMap: "flow-parameters"
  sensitiveParameterContextMap: "flow-sensitive-parameters"
---
apiVersion: v1
kind: Secret
metadata:
  name: flow-sensitive-parameters
stringData:
  sensitiveValue1: xyz
  sensitiveValue2: xyz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-parameters
stringData:
  value1: xyz
  value2: xyz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-flow-template
data: |
   < xml flow representation >
```

So the associated workflow would look like follows:

- Create flow in NiFi, parameterize, export and download as template
- Upload template to configmap
- Create values ConfigMap & sensitive values Secret
- Create NifiFlow object

The limitations of this implementation would be that we only ever can create these flows, there won't be any updates when the template changes in K8s.


I am beginning to question whether given the complexity of the above workflow, coupled with the limitations make the implementation of this feature worthwhile, especially if we can make do with a manually created Job object for our demos to provision workflows, which would effectively do the same thing.

Paging @Jimvin and @lfrancke  for comment
