### ISSUE TITLE
Document how to include custom processors in a Stackable NiFi deployment

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/nifi-operator#229]
### Discussed in https://github.com/stackabletech/nifi-operator/discussions/225

<div type='discussions-op-text'>

<sup>Originally posted by **Jimvin** March  1, 2022</sup>
I would like a way to include custom assets, such as JDBC drivers, libraries and custom NiFi processors in my cluster. I would like to do this in a way that ensures all of the instances in the cluster contain the same assets.</div>

**Comment by deebify** [comment]
I want to do the same as well. I suggest extending the docker image used by stackable. 
https://github.com/stackabletech/docker-images/blob/main/nifi/Dockerfile

and publish it in my local docker registry and instruct the NiFi CRDs to use my docker registry image instead. 

Is that going to work? Any thoughts?

**Comment by maltesander** [comment]
> I want to do the same as well. I suggest extending the docker image used by stackable. https://github.com/stackabletech/docker-images/blob/main/nifi/Dockerfile
> 
> and publish it in my local docker registry and instruct the NiFi CRDs to use my docker registry image instead.
> 
> Is that going to work? Any thoughts?

Yes that should work. You could then use `image.custom` to reference your docker registry (https://docs.stackable.tech/home/stable/concepts/product_image_selection.html#_custom_images) and tag.

**Comment by lfrancke** [comment]
This might come down to just docs but we should check if there's a more convenient way to do this.

**Comment by soenkeliebau** [comment]
Ideally I'd like to add something to the NiFi CRD that gives the option of adding custom processors with more convenience.

Something like:

```yaml
---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi
spec:
  clusterConfig:
    customProcessors:
      - fetchUrl:
          url: http://my-company/repo/processor.nar
          checksum: 12345
      - persistentVolumeClaim
          name: my-pvc-containing-processors
      - gitReference
           git: git:// ....
```

None of this is fully thought through, but I think specifying external stuff may come up more than once, this might be something worth abstracting over as it is basically just a way of saying "I need this on the classpath please".
