### ISSUE TITLE
adminCredentialsSecret -> no namespace and remove the name property to make it “top-level”

### ISSUE THREAD

**Issue by fhennig** [stackabletech/nifi-operator#233]
This is done when
- [ ] `adminCredentialsSecret` is a string and no `SecretReference` anymore
- [ ] documentation, examples and integration tests have been updated

This means we can only reference Secrets in our own namespace and not other namespaces anymore.

```
  authenticationConfig:
    method:
      SingleUser:
        adminCredentialsSecret: nifi-admin-credentials-simple
        autoGenerate: true
```

NOTE: It might make sense to do this together with #234 and #235
