### ISSUE TITLE
authenticationConfig & sensitivePropertiesConfig -> top level config object

### ISSUE THREAD

**Issue by fhennig** [stackabletech/nifi-operator#235]
This is done when
- [ ] the two `authenticationConfig` & `sensitivePropertiesConfig` settings have been moved into a top-level `config` object (see example below)
- [ ] documentation, examples and integration tests have been updated

NOTE: It might make sense to do this together with #234

NOTE: Please talk to @soenkeliebau first because we had a discussion about product config and the result isn't written down anywhere

Example:
```
spec:
  version: "1.15.0"
  zookeeperConfigMapName: simple-nifi-znode
  config:
    authentication:
      method:
        SingleUser:
          adminCredentialsSecret:
            name: nifi-admin-credentials-simple
          autoGenerate: true
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
```
