### ISSUE TITLE
I can't understand how increase pvc in nificluster

### ISSUE THREAD

**Issue by grandeon** [stackabletech/nifi-operator#474]
Hi everybody,

I'm trying to increase the deafult pvc for a nifi cluster but I can't got it.
This is the configuration I'm using: 

```yaml
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: apm-nifi
  namespace: nifi-experiments
spec:
  image:
    productVersion: "1.18.0"
    stackableVersion: "23.4.0"
  clusterConfig:
    listenerClass: cluster-internal
    authentication:
      method:
        singleUser:
          adminCredentialsSecret: nifi-admin-credentials-apm
          autoGenerate: false
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
    zookeeperConfigMapName: apm-nifi-znode
  nodes: # role-level
    config:
      resources:
        cpu:
          min: "500m"
          max: "4"
        memory:
          limit: "8Gi"
    roleGroups: # role-group-level
      base: # role-group 1
        replicas: 0
      high: # role-group 2
        replicas: 1
        config:
          resources:
            storage:
              flowfile_repo:
                capacity: "12Gi"
              provenance_repo:
                capacity: "12Gi"
              database_repo:
                capacity: "12Gi"
              content_repo:
                capacity: "12Gi"
              state_repo:
                capacity: "12Gi"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - nifi
        configOverrides:
          nifi.properties:
            nifi.web.proxy.host: "nifi.xxxx.xxxx.com:443"
```
The configOverrides section works fine.
I can increase the cpu and memory  resources, but not the storage. Always I get the default pvc size.

What is my misconfiguration?
Can someone help me?

Thank you so much!!
