### ISSUE TITLE
Facing issue Invalid SNI while accessing NIFI running on AKS with ingress  using Nginx ingress controller from ALB

### ISSUE THREAD

**Issue by loginvarun** [stackabletech/nifi-operator#697]
### Affected Stackable version

24.7.0 

### Affected Apache NiFi version

2.0.0-M4

### Current and expected behavior

My NiFi version 1.27.0 is working fine on version 24.7.0. When we did update to 2.0.0-M4 Nifi version, NiFi URL erroring out with invalid SNI.

Below blog advised to regenerate certificate:
https://medium.com/@chnzhoujun/how-to-resolve-sni-issue-when-upgrading-to-nifi-2-0-907e07d465c5#:~:text=Due%20to%20the%20upgrade%20to,400%3A%20Invalid%20SNI%20will%20occur

Please help in debugging:
**Below is the output of from pod itself:**
```
curl -k https://10.170.57.114:8443
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Invalid SNI</title>
</head>
<body>
<h2>HTTP ERROR 400 Invalid SNI</h2>
<table>
<tr><th>URI:</th><td>https://10.170.57.114:8443/</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Invalid SNI</td></tr>
</table>

</body>
</html>
```

Ingress Manifest
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:

  labels:
    k8slens-edit-resource-version: v1
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - xxxx.int.zzzz.com
      secretName: ssl-cert
  rules:
    - host: xxxx.int.zzzz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nifi-cluster-reporting-task
                port:
                  number: 8443
```

### Environment

Server Version: v1.30.3
nginx-ingress-controller:v1.11.2

### Would you like to work on fixing this bug?

None

**Comment by sbernauer** [comment]
Hi @loginvarun!

Funny thing, I ran into the same problem last week. I solved it by telling nginx to use the fqdn instead of only the service name (by setting the annotation `nginx.ingress.kubernetes.io/upstream-vhost: "nifi.default.svc.cluster.local"`).
We also had the idea of patching the NiFi code to disable the check, do you think that's a good idea? It sounds like a tradeoff between security and usability to me.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    # Maybe(!) remove and switch to http
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # Work around https://medium.com/@chnzhoujun/how-to-resolve-sni-issue-when-upgrading-to-nifi-2-0-907e07d465c5
    # We need to use the FQDN, so that NiFi has a cert for the host and does not throw
    # HTTP ERROR 400 Invalid SNI
    nginx.ingress.kubernetes.io/upstream-vhost: "nifi.default.svc.cluster.local"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nifi.xxx.de
    secretName: ingress-nifi
  rules:
  - host: nifi.xxx.de
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nifi
            port:
              number: 8443
```
